# Generated by Django 4.1.6 on 2023-02-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('school_admin', '0009_subjects_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studentname', models.CharField(max_length=20)),
                ('Studentemail', models.CharField(max_length=20, unique=True)),
                ('Studentdob', models.CharField(max_length=20)),
                ('Studentmob', models.BigIntegerField(unique=True)),
                ('Studentguardian', models.CharField(max_length=20)),
                ('Studentadress', models.CharField(max_length=50)),
                ('Studentimage', models.ImageField(default='static/images/student.png', upload_to='student/')),
                ('Student_gender', models.CharField(max_length=10)),
                ('Studentclass', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school_admin.classdivision')),
                ('authorize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.login')),
            ],
        ),
        migrations.CreateModel(
            name='Studentfees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_paid', max_length=20)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.students')),
            ],
        ),
    ]
