# Generated by Django 4.1.6 on 2023-02-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0009_subjects_fees'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.BigIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.subjects')),
            ],
        ),
    ]
