# Generated by Django 4.1.6 on 2023-02-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        ('Teacher', '0002_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='principal.exams'),
        ),
    ]
