# Generated by Django 4.1.6 on 2023-02-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('school_admin', '0002_alter_addstaff_staff_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.login')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.addstaff')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.login')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.addstaff')),
            ],
        ),
    ]
