# Generated by Django 4.1.6 on 2023-02-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0005_alter_salary_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_capacity', models.PositiveBigIntegerField()),
                ('Section', models.CharField(max_length=3)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.classroom')),
            ],
        ),
    ]
