# Generated by Django 4.1.6 on 2023-02-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0006_classroom_classdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_admin.addstaff'),
        ),
    ]
