# Generated by Django 4.1.6 on 2023-02-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0008_classdivision_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjectname', models.CharField(max_length=20)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feesname', models.CharField(max_length=20)),
                ('Amount', models.BigIntegerField(default=0)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.classroom')),
            ],
        ),
    ]
